server.port=8090
spring.application.name=ms-restricciones

# Configuración de Base de Datos (Conectando al contenedor Docker)
spring.datasource.url=jdbc:mysql://localhost:3320/bd_restricciones?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Seguridad y JWT
jwt.secret=ClaveUltraSecretaEInviolableParaLaMunicipalidad2026!
jwt.issuer=ms-auth

# 🚀 ESTRATEGIA MS-CANCHAS: Sincronización milimétrica del JSON de OpenAPI
springdoc.api-docs.path=/api/v1/restricciones/v3/api-docs

# Habilitamos la UI local por si acaso
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# 🛠️ SOLUCCIÓN AL SEGUIMIENTO DE CAPA DE SEGURIDAD (AOP / @PreAuthorize)
# Permite que Springdoc ignore las restricciones de roles al generar los esquemas de documentación
springdoc.api-docs.resolve-schema-properties=true
springdoc.webjars.prefix=/webjars
springdoc.show-actuator=false